Repository blackberggroup/VA-Hackathon, pull requests merged in 2024-03, with the labels that each got.

#1 Feature/rp 2900391831/registration form
  .github/workflows/deploy-dev-sandbox.yml
  .github/workflows/deploy-sandbox.yml
  _includes/form-registration/form-section1.html
  _includes/form-registration/form-section2.html
  _includes/form-registration/form-section3.html
  _includes/form-registration/form-section4.html
  _includes/form-registration/form-sectionC.html
  _includes/form-registration/form-sectionTY.html
  _site/.github/PULL_REQUEST_TEMPLATE/index.html
  _site/assets/css/styles.css
  _site/assets/js/parsley-functions.js
  _site/assets/js/vendors/multiselect/multiselect-dropdown.js
  _site/assets/js/vendors/parsley/parsley.min.js
  _site/assets/sass/styles.scss
  _site/assets/sass/vha/pages/_index.scss
  _site/assets/sass/vha/pages/participant-registration/_index.scss
  _site/assets/sass/vha/pages/thank-you/_index.scss
  _site/assets/uswds/img/correct8.svg
  _site/assets/uswds/img/usa-icons/arrow_back.svg
  _site/assets/uswds/img/usa-icons/correct8.svg
  _site/assets/uswds/img/usa-icons/dropdown-line.svg
  _site/assets/uswds/img/usa-icons/line_and_arrow.svg
  _site/assets/uswds/img/usa-icons/navigate_next.svg
  _site/participant-registration/index.html
  _site/thank-you/index.html
  assets/css/styles.css
  assets/js/parsley-functions.js
  assets/js/vendors/multiselect/multiselect-dropdown.js
  assets/js/vendors/parsley/parsley.min.js
  assets/sass/styles.scss
  assets/sass/vha/pages/_index.scss
  assets/sass/vha/pages/participant-registration/_index.scss
  assets/sass/vha/pages/thank-you/_index.scss
  assets/uswds/img/correct8.svg
  assets/uswds/img/usa-icons/arrow_back.svg
  assets/uswds/img/usa-icons/line_and_arrow.svg
  assets/uswds/img/usa-icons/navigate_next.svg
  participant-registration/index.html
  thank-you/index.html
Labels: enhancement, ready for review

#3 <bugfix: fixed and updated w/ monday item requests; pending real numb…
  _includes/form-registration/form-section1.html
  _includes/form-registration/form-section2.html
  _includes/form-registration/form-section3.html
  _includes/form-registration/form-section4.html
  _includes/form-registration/form-sectionC.html
  _site/assets/css/styles.css
  _site/assets/js/parsley-functions.js
  _site/assets/sass/vha/pages/participant-registration/_index.scss
  _site/participant-application/index.html
  assets/css/styles.css
  assets/js/parsley-functions.js
  assets/sass/vha/pages/participant-registration/_index.scss
  participant-application/index.html
Labels: bug, ready for review

#6 Bugfix/jls 6292521834/post production updates
  _includes/header-sub.html
  _includes/header.html
  _site/assets/documents/NC4TI Hackathon Flyers-Final-QR.pdf
  _site/assets/img/home/tampa-va-medical-center-badge.pngtampa-va-medical-center-badge.png.tampa-va-medical-center-badge.png
  _site/assets/js/vendors/wavesjs/jquery.wavify.js
  _site/assets/js/vendors/wavesjs/wavify.js
  _site/index.html
  _site/participant-application/index.html
  _site/thank-you/index.html
  assets/img/home/tampa-va-medical-center-badge.pngtampa-va-medical-center-badge.png.tampa-va-medical-center-badge.png
Labels: bug, ready for review

#7 fix-6348604598-removed char count max length
  _includes/form-registration/form-section3.html
  _includes/form-registration/form-section4.html
  _site/participant-application/index.html
Labels: ready for review
